from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import hashlib
import json

from .io import read_text_if_exists
from .loader import WorkspaceIndex, load_workspace


TEXT_SUFFIXES = {".md", ".rst", ".txt", ".yaml", ".yml"}
CHUNK_CHAR_LIMIT = 1600
MIN_CHUNK_SPLIT = 400


def default_vector_index_path(workspace_root: Path) -> Path:
    return workspace_root / "indexes" / "vector_sources.json"


def default_vector_chunks_path(workspace_root: Path) -> Path:
    return workspace_root / "indexes" / "vector_chunks.json"


def rebuild_vector_index(path: str | Path = ".aiteamos", output_path: str | Path | None = None) -> dict[str, Any]:
    index = load_workspace(path)
    target = Path(output_path).expanduser().resolve() if output_path else default_vector_index_path(index.workspace_root)
    chunk_target = target.with_name("vector_chunks.json")
    entries, chunks = build_vector_index_records(index)
    manifest = {
        "kind": "DerivedVectorSourceManifest",
        "schemaVersion": "aiteamos.vector-sources/v1",
        "workspaceRoot": str(index.workspace_root),
        "source": str(index.workspace_root),
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "derived": True,
        "contentStored": False,
        "embeddingsGenerated": False,
        "embeddingModel": None,
        "entries": entries,
        "counts": _counts(entries),
        "chunkManifest": str(chunk_target),
        "chunkCount": len(chunks),
        "notes": [
            "This manifest records deterministic source references and content hashes only.",
            "Embedding generation is intentionally not performed by this rebuild command.",
        ],
    }
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(manifest, sort_keys=True, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    chunk_manifest = {
        "kind": "DerivedVectorChunkManifest",
        "schemaVersion": "aiteamos.vector-chunks/v1",
        "workspaceRoot": str(index.workspace_root),
        "source": str(index.workspace_root),
        "generatedAt": manifest["generatedAt"],
        "derived": True,
        "contentStored": False,
        "embeddingsGenerated": False,
        "embeddingModel": None,
        "chunking": {
            "strategy": "deterministic-char-window",
            "charLimit": CHUNK_CHAR_LIMIT,
            "minSplit": MIN_CHUNK_SPLIT,
        },
        "chunks": chunks,
        "counts": _counts(chunks),
        "notes": [
            "Chunks record deterministic spans and hashes only; no source text is stored.",
            "Embeddings are not generated by this rebuild command.",
        ],
    }
    chunk_target.write_text(json.dumps(chunk_manifest, sort_keys=True, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    manifest["path"] = str(target)
    manifest["chunkManifestPath"] = str(chunk_target)
    return manifest


def build_vector_index_records(index: WorkspaceIndex) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    return _collect_vector_sources(index)


def _collect_vector_sources(index: WorkspaceIndex) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    entries: list[dict[str, Any]] = []
    chunks: list[dict[str, Any]] = []

    for entry_id, entry in sorted(index.memory_entries.items()):
        if entry.spec.lifecycle != "active":
            continue
        if entry.spec.sensitivity == "secret":
            continue
        store = index.memory_stores.get(entry.spec.store)
        _append_source(
            entries,
            chunks,
            kind="memory_entry",
            source_ref=f"memory/entries/{entry_id}.yaml",
            text="\n".join([entry.spec.title, entry.spec.content, "\n".join(entry.spec.evidence), "\n".join(entry.spec.tags)]),
            project=_first(entry.spec.relatedProjects) or (store.spec.ownerProject if store else None) or index.project.object_id,
            member=_first(entry.spec.relatedMembers) or (store.spec.ownerMember if store else None),
            assignment=_first(entry.spec.relatedAssignments),
            store=entry.spec.store,
            title=entry.spec.title,
            memory=entry_id,
        )

    for task_id, text in sorted(index.task_markdown.items()):
        task = index.tasks.get(task_id)
        _append_source(
            entries,
            chunks,
            kind="task_markdown",
            source_ref=f"tasks/{task_id}.md",
            text=text,
            project=task.spec.project if task else index.project.object_id,
            member=task.spec.assignedMember if task else None,
            assignment=task.spec.assignment if task else None,
            title=task.spec.title if task else task_id,
            task=task_id,
        )

    for run_id, text in sorted(index.run_journals.items()):
        run = index.runs.get(run_id)
        _append_source(
            entries,
            chunks,
            kind="run_journal",
            source_ref=f"runs/{run_id}/journal.md",
            text=text,
            project=run.spec.project if run else index.project.object_id,
            member=run.spec.member if run else None,
            assignment=run.spec.assignment if run else None,
            title=run_id,
            task=run.spec.task if run else None,
            run=run_id,
        )

    for review_id, text in sorted(index.review_markdown.items()):
        review = index.reviews.get(review_id)
        _append_source(
            entries,
            chunks,
            kind="review_markdown",
            source_ref=f"reviews/{review_id}.md",
            text=text,
            project=review.spec.project if review else index.project.object_id,
            member=review.spec.reviewerMember if review else None,
            assignment=None,
            title=review_id,
            task=review.spec.task if review else None,
            run=review.spec.run if review else None,
            review=review_id,
        )

    for source in _doc_sources(index):
        _append_source(entries, chunks, **source)

    entries.sort(key=lambda item: (item["kind"], item["sourceRef"]))
    chunks.sort(key=lambda item: (item["kind"], item["sourceRef"], item["chunkIndex"]))
    return entries, chunks


def _doc_sources(index: WorkspaceIndex) -> list[dict[str, Any]]:
    entries = list(index.project.spec.ruleEntrypoints)
    for fallback in ["README.md", "docs/architecture.md"]:
        if fallback not in entries:
            entries.append(fallback)

    sources: list[dict[str, Any]] = []
    for repo in index.repositories.values():
        root = _repo_root(index, repo)
        if root is None:
            continue
        for rel in dict.fromkeys(entries):
            path = (root / rel).resolve()
            if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES or not _is_safe_relative(root, path):
                continue
            text = read_text_if_exists(path)
            if text is None:
                continue
            sources.append(
                {
                    "kind": "project_doc",
                    "source_ref": f"repo:{repo.object_id}:{rel}",
                    "text": text,
                    "project": index.project.object_id,
                    "member": None,
                    "assignment": None,
                    "title": rel,
                }
            )
    return sources


def _append_source(
    entries: list[dict[str, Any]],
    chunks: list[dict[str, Any]],
    *,
    kind: str,
    source_ref: str,
    text: str,
    project: str | None,
    member: str | None,
    assignment: str | None,
    title: str | None = None,
    task: str | None = None,
    run: str | None = None,
    review: str | None = None,
    memory: str | None = None,
    store: str | None = None,
) -> None:
    content = text or ""
    source_id = _source_id(kind, source_ref)
    source_chunks = _chunk_source(
        source_id=source_id,
        kind=kind,
        source_ref=source_ref,
        content=content,
        project=project,
        member=member,
        assignment=assignment,
        task=task,
        run=run,
        review=review,
        memory=memory,
        store=store,
        title=title,
    )
    entries.append(
        {
            "id": source_id,
            "kind": kind,
            "sourceRef": source_ref,
            "project": project,
            "member": member,
            "assignment": assignment,
            "task": task,
            "run": run,
            "review": review,
            "memory": memory,
            "store": store,
            "title": title,
            "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
            "byteLength": len(content.encode("utf-8")),
            "chunkCount": len(source_chunks),
            "contentStored": False,
            "embeddingStatus": "pending-provider",
        }
    )
    chunks.extend(source_chunks)


def _chunk_source(
    *,
    source_id: str,
    kind: str,
    source_ref: str,
    content: str,
    project: str | None,
    member: str | None,
    assignment: str | None,
    task: str | None,
    run: str | None,
    review: str | None,
    memory: str | None,
    store: str | None,
    title: str | None,
) -> list[dict[str, Any]]:
    chunks: list[dict[str, Any]] = []
    for index, (start, end, chunk) in enumerate(_chunk_spans(content)):
        chunk_hash = hashlib.sha256(chunk.encode("utf-8")).hexdigest()
        chunks.append(
            {
                "id": _chunk_id(source_id, index, chunk_hash),
                "sourceId": source_id,
                "kind": kind,
                "sourceRef": source_ref,
                "project": project,
                "member": member,
                "assignment": assignment,
                "task": task,
                "run": run,
                "review": review,
                "memory": memory,
                "store": store,
                "title": title,
                "chunkIndex": index,
                "charStart": start,
                "charEnd": end,
                "sha256": chunk_hash,
                "byteLength": len(chunk.encode("utf-8")),
                "tokenEstimate": max(1, len(chunk) // 4),
                "contentStored": False,
                "embeddingStatus": "pending-provider",
            }
        )
    return chunks


def _chunk_spans(content: str) -> list[tuple[int, int, str]]:
    if not content.strip():
        return []
    spans: list[tuple[int, int, str]] = []
    start = 0
    length = len(content)
    while start < length:
        end = min(length, start + CHUNK_CHAR_LIMIT)
        if end < length:
            boundary = content.rfind("\n\n", start, end)
            if boundary <= start + MIN_CHUNK_SPLIT:
                boundary = content.rfind("\n", start, end)
            if boundary > start + MIN_CHUNK_SPLIT:
                end = boundary + 1
        chunk = content[start:end]
        if chunk.strip():
            spans.append((start, end, chunk))
        start = max(end, start + 1)
    return spans


def _source_id(kind: str, source_ref: str) -> str:
    digest = hashlib.sha256(f"{kind}:{source_ref}".encode("utf-8")).hexdigest()
    return f"VS-{digest[:16]}"


def _chunk_id(source_id: str, chunk_index: int, chunk_hash: str) -> str:
    digest = hashlib.sha256(f"{source_id}:{chunk_index}:{chunk_hash}".encode("utf-8")).hexdigest()
    return f"VC-{digest[:16]}"


def _counts(entries: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {"total": len(entries)}
    for entry in entries:
        key = entry["kind"]
        counts[key] = counts.get(key, 0) + 1
    return counts


def _first(values: list[str]) -> str | None:
    return values[0] if values else None


def _repo_root(index: WorkspaceIndex, repo: Any) -> Path | None:
    if repo.spec.localPath:
        root = Path(repo.spec.localPath).expanduser()
        if not root.is_absolute():
            root = index.workspace_root.parent / root
    else:
        root = index.workspace_root.parent
    root = root.resolve()
    return root if root.exists() and root.is_dir() else None


def _is_safe_relative(root: Path, path: Path) -> bool:
    try:
        path.relative_to(root.resolve())
    except ValueError:
        return False
    return not any(part in {".git", ".aiteamos", "node_modules", "dist", "build"} for part in path.parts)
